### ISSUE TITLE
Possible without a SmartCom

### ISSUE THREAD

**Issue by madmic1314** [dchesterton/texecom2mqtt-hassio#1]
Just a note that I have got this working using a Pi and a USB to serial adapter. I'll try and look up the exact process, but you can expose a serial port to the network for read/write. Your HA add-in recognised this and we're cooking on gas!

Thank you for the add-in - much appreciated!

**Comment by mrwee** [comment]
I've got communication running using a Moxa serial to IP gateway. Just configure the Panel port to "Nothing fitted". Serial is: 19200,N,8,1.
