### ISSUE TITLE
Email Alerts / Push App Alerts form Texecom Cloud (not really an issue i think)

### ISSUE THREAD

**Issue by rob1981forest** [dchesterton/texecom2mqtt-hassio#16]
Hi, 

Recently got a new Texecom alarm installed and got this setup and working great however i seem to get a flood of email / app alerts at certain points in the day from the texecom cloud service that have stacked up from past arms/disarms.

Is it a case that my texecom2mqtt has a slight blip, the system then connects up to the cloud and pushes me these alerts ? It seems to allow me to arm / disarm via the cloud app all the time so im not sure whats going on.

I have the SmartCom module but i read others have both the SmartCom and the ComIP module - is this to somehow get around this ?

Thanks a lot

Rob

**Comment by perimore** [comment]
I believe you can/should only use one or the other. My guess is the cloud
app is trying to connect and when texecom2mqtt gives up the connection, the
cloud service gets through and sends the queued messages.

Sean

**Comment by dchesterton** [comment]
Yeah only one service can connect to a SmartCom/ComIP at a time so I expect that's why you're getting odd behaviour.

I'd recommend getting another SmartCom or a ComIP and use that exclusively for texecom2mqtt or disable the cloud functionality.
