### ISSUE TITLE
Insecure secrets in c15a2434_texecom2mqtt

### ISSUE THREAD

**Issue by rob1981forest** [dchesterton/texecom2mqtt-hassio#17]
Hi,

Last night HA started to alert me with this.

Insecure secrets in c15a2434_texecom2mqtt
The add-on c15a2434_texecom2mqtt uses secrets which are detected as not secure, see https://www.home-assistant.io/more-info/pwned-passwords for more information.

Is this something in the code or something in one of the passwords i've set (like for my mqtt user) ?

**Comment by dchesterton** [comment]
Yeah, it will be one of your passwords that it's considering insecure. It will likely be either your UDL code or your MQTT password.
