### ISSUE TITLE
Panel disconnected - keeps running

### ISSUE THREAD

**Issue by madmic1314** [dchesterton/texecom2mqtt-hassio#18]
**Describe the bug**
I'm running Ser2Net on a Pi to act as a bridge between the LAN and serial port. This is rock solid, but if I reboot my WiFi router Ser2Net exits requiring the Pi to be rebooted or the process to be restarted. I'm looking at fixing this locally on the Pi, but got thinking...

Whilst this isn't an issue directly with this software, texecome2mqtt continues running with a log message of "Panel Disconnected". Rebooting the Pi bring it back online again.

It would be great if this could trigger an exit of the software, so I can detect something is wrong or maybe set an abnormal flag which we can monitor for?

**Application version**
1.0.38

**Texecom alarm type**
Premier Elite 24

**Home Assistant version**
2021.3.4

**Debug log**
N/A.

**Comment by dchesterton** [comment]
Thanks for your report. I've pushed a new update which should fix this issue. Please open another if you continue to have problems.
