### ISSUE TITLE
Time setting with texecom2mqtt-hassio

### ISSUE THREAD

**Issue by MikeLDPT** [dchesterton/texecom2mqtt-hassio#19]
Hi.  

I configured and started this up this morning (V1.0.39) and have successfully connected to the alarm system (a few hiccups as recorded below).  Whilst it is now "up and running" in HASSIO, It seems that when an event occurs (e.g. a door is opened which breaks the contacts), as well as reporting the event, the HASSIO logbook also seems to record that: Internet Time, Date & Time (UTC), Date & Time, Time and Date, Date & Time (ISO), and Time are all logged as being changed.

I notice that, in the start up log of texecom2mqtt, all tmes are stated as UTC rather than BST.  Is there a connection with something texecom2mqtt does?

I am being a little over cautious perhaps going forward with this as the first attempt at starting texecom2mqtt, the alarm entered a system fault mode with UDL locked out.  I also had a subsequent system fault reportedly on a wireless sensor that lost connection which bizarrely seemed to be from looking at timestamps during the startup.  These alarm "faults" requied an alarm co. engineer reset.....and cause was left as "unknown". 

Thanks.
![image](https://user-images.githubusercontent.com/70011875/113731069-5eb26880-96f0-11eb-96ae-170738b89ccf.png)

**Comment by dchesterton** [comment]
Hi Mike,

Those date/time changes are nothing to do with the app. The app only integrates with Home Assistant via an MQTT broker so it doesn't have access to change anything regarding date/time.

I'm not sure what caused the UDL lock out but I'd assume it might have been an incorrect UDL password?

Let me know if you have any further problems but I'm going to close this for now.
