### ISSUE TITLE
Integration becomes unavailable   

### ISSUE THREAD

**Issue by gtakarting** [dchesterton/texecom2mqtt-hassio#26]
No sure what my issue is, probably something i am doing wrong. Integration work great Texecom log file updates all the information correctly no problem there. Its the mqtt server suddenly stops receiving the posts. i have to uninstall the mqtt and Texecom and reinstall for it to work again. 
I am using Mosquitto broker Current version: 6.0.1 (Changelog), texecom2mqtt Current version: 1.1.5 (Changelog)

Texecom Code
--
texecom:
  host: xx
  udl_password: 'xx'
mqtt:
  host: core-mosquitto
homeassistant:
  discovery: true
areas: []
zones: []
--
Log
--
2021-09-12 07:46:54 - INFO: ABV FNT DOOR PIR status changed to Secure
2021-09-12 07:47:03 - INFO: ABV FNT DOOR PIR status changed to Active
2021-09-12 07:47:06 - INFO: ABV FNT DOOR PIR status changed to Secure
2021-09-12 07:47:13 - INFO: ABV FNT DOOR PIR status changed to Active
2021-09-12 07:47:15 - INFO: ABV FNT DOOR PIR status changed to Secure
2021-09-12 07:49:46 - INFO: ABV FNT DOOR PIR status changed to Active
2021-09-12 07:49:46 - INFO: DOWNSTAIRS HALL status changed to Active
2021-09-12 07:49:47 - INFO: ABV FNT DOOR PIR status changed to Secure
2021-09-12 07:49:49 - INFO: LIVING ROOM status changed to Active
2021-09-12 07:49:50 - INFO: DOWNSTAIRS HALL status changed to Secure
2021-09-12 07:49:53 - INFO: LIVING ROOM status changed to Secure
2021-09-12 07:50:35 - INFO: LIVING ROOM status changed to Active
2021-09-12 07:50:39 - INFO: LIVING ROOM status changed to Secure
--
Mosquitto broker
--
logins: []
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
--
log
--[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] mosquitto.sh: executing... 
[08:35:58] INFO: SSL is not enabled
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[08:35:59] INFO: Starting NGINX for authentication handling...
[08:35:59] INFO: Starting mosquitto MQTT broker...
1631432159: mosquitto version 1.6.12 starting
1631432159: |-- *** auth-plug: startup
[08:36:00] INFO: Successfully send discovery information to Home Assistant.
[08:36:01] INFO: Successfully send service information to the Supervisor.
1631432159: Config loaded from /etc/mosquitto/mosquitto.conf.
1631432159: Loading plugin: /usr/share/mosquitto/auth-plug.so
1631432159:  ├── Username/password checking enabled.
1631432159:  ├── TLS-PSK checking enabled.
1631432159:  └── Extended authentication not enabled.
1631432159: Opening ipv4 listen socket on port 1883.
1631432159: Opening ipv6 listen socket on port 1883.
1631432159: Opening websockets listen socket on port 1884.
1631432160: Warning: Mosquitto should not be run as root/administrator.
1631432160: mosquitto version 1.6.12 running
1631432160: New connection from 127.0.0.1 on port 1883.
1631432160: Socket error on client <unknown>, disconnecting.
1631432160: New connection from 172.30.32.1 on port 1883.
1631432160: New client connected from 172.30.32.1 as 1BshYnM9af9E7PQOGJizVO (p2, c1, k60, u'homeassistant').
1631432166: New connection from 192.168.1.126 on port 1883.
{"result": "ok", "data": {}}1631432166: New client connected from 192.168.1.126 as DVES_4C72EF (p2, c1, k30, u'mqttuser').
1631432166: New connection from 192.168.1.216 on port 1883.
1631432166: New client connected from 192.168.1.216 as DVES_C3A8D7 (p2, c1, k30, u'mqttuser').
1631432166: New connection from 192.168.1.113 on port 1883.
1631432166: New client connected from 192.168.1.113 as DownStairsHall (p2, c1, k30, u'mqttuser').
1631432172: New connection from 172.30.33.3 on port 1883.
1631432172: New client connected from 172.30.33.3 as mqttjs_d17c2c62 (p2, c1, k10).
1631432209: Client DownStairsHall disconnected.
1631432210: Client DVES_4C72EF disconnected.
1631432212: Client DVES_C3A8D7 disconnected.
1631432216: New connection from 192.168.1.113 on port 1883.
1631432216: New client connected from 192.168.1.113 as DownStairsHall (p2, c1, k30, u'mqttuser').
1631432219: New connection from 192.168.1.126 on port 1883.
1631432219: New client connected from 192.168.1.126 as DVES_4C72EF (p2, c1, k30, u'mqttuser').
1631432224: New connection from 192.168.1.216 on port 1883.

**Comment by dchesterton** [comment]
I've managed to get to the bottom of this bug and it has _finally_ been fixed in v1.2.0. Closing this.
