### ISSUE TITLE
Anybody got it working with v5.04?

### ISSUE THREAD

**Issue by fedortche** [dchesterton/texecom2mqtt-hassio#3]
I'm getting following in the log. Encryption is not enabled, default 1234 is working.
I've send an email to Texecom asking if protocol has any changes in v5, we'll see.
(also I'm using Pi with ser2net instead of ComIP)

2020-10-04 17:25:01 - INFO: Connected to alarm, sleeping for 0.5 seconds...
2020-10-04 17:25:02 - INFO: Connection ready
2020-10-04 17:25:02 - INFO: Fetched serial number: #######
2020-10-04 17:25:02 - INFO: Logging in
2020-10-04 17:25:02 - INFO: Successfully logged in
2020-10-04 17:25:02 - ERROR: Unhandled rejection - Error: Connection refused: Not authorized

**Comment by madmic1314** [comment]
Hopefully the dev will drop by soon - but I'm on 5.00 (or 5.01), if that helps. Was thinking of upgrading to latest, but will hang on. Are you sure your UDL password is 1234?

Can you downgrade the firmware? I believe you can, if you have the flashing unit. Might be worth going to 5.00 and trying that. Hopefully Texecom will shed some light - they're really prickly about giving out the protocol documentation now. I tried - they rejected me. Apparently I'm not developer enough for them!

**Comment by bensuffolk** [comment]
Working great for me:

`2020-10-29 21:46:52 - INFO: Fetched panel info: Premier Elite 24 (V5.04.01LS1) `

**Comment by bensuffolk** [comment]
I think the error you are seeing is not related to the alarm, but an auth error connecting to MQTT, so check your mosquito logs.  I imagine you will see an error there.

**Comment by mrwee** [comment]
It works for me on an Elite 168 panel.
