### ISSUE TITLE
Undefined property prevents container to start

### ISSUE THREAD

**Issue by grillsoftware** [dchesterton/texecom2mqtt-hassio#35]
I fixed the previous issue based on your comments but now I'm getting a type error.

I found references to this issue in past issue reports but didn't help much. I even tried adding the zones and areas to the config file but nothing.

Here's the latest config with few tweaks:
texecom:
    # Required: Texecom panel IP address
    host: {{texecom_panel_ip}}
    # Optional: UDL password programmed in the panel. Note: this is NOT the code used to arm/disarm the panel (default: 1234)
    udl_password: {{texecom_panel_udl_pass}}
    # Optional: port used to connect to the panel (default: 10001)
    port: 10001

mqtt:
    # Optional: broker URL or IP address (default: localhost)
    host: localhost
    # Optional: broker port (default: 1883 or 8883 for TLS connections)
    port: 1883
    # Optional: topic prefix to use (default: texecom2mqtt)
    prefix: texecom2mqtt
    #username: my_user # Optional: broker user (default: none)
    #password: my_password # Optional: broker password (default: none)
    # Optional: client ID (default: random)
    client_id: texecom2mqtt
    # Optional: keepalive in seconds (default: 10)
    keepalive: 30
    # Optional: retain (default: true)
    retain: true
    # Optional: retain on log messages (default: false)
    retain_log: false
    # Optional: QoS (default: 0)
    qos: 2
    #ca: /cert/ca.pem # Optional: CA for TLS connection (default: none)
    #cert: /cert/cert.pem # Optional: certificate for TLS connection (default: none)
    #key: /cert/key.pem # Optional: private key for TLS connection (default: none)

homeassistant:
    # Optional: enable Home Assistant discovery (default: false)
    discovery: true
    # Optional: Home Assistant MQTT topic prefix (default: homeassistant)
    #prefix: homeassistant 
    
log: debug

**Debug Log**
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1),
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.,
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of undefined,
    at /snapshot/app/node_modules/better-ajv-errors/lib/modern/helpers.js:26:53,
    at Array.forEach (<anonymous>),
    at makeTree (/snapshot/app/node_modules/better-ajv-errors/lib/modern/helpers.js:21:13),
    at _default (/snapshot/app/node_modules/better-ajv-errors/lib/modern/helpers.js:116:16),
    at _default (/snapshot/app/node_modules/better-ajv-errors/lib/modern/index.js:27:45),
    at validate (/snapshot/app/dist/config.js:58:24),
    at Object.loadConfig (/snapshot/app/dist/config.js:41:16),
    at /snapshot/app/dist/index.js:11:29,
    at Object.<anonymous> (/snapshot/app/dist/index.js:74:3),
    at Module._compile (pkg/prelude/bootstrap.js:1433:22)

I looked in the closed issues and found one with the same error message. It was fixed by mapping the correct arming modes of the areas. However, I have no areas or zones configured yet as the documentation states they are optional.
https://github.com/dchesterton/texecom2mqtt-hassio/issues/30

I tried adding areas: [] and zones: [] but it didn't help.

I have no visual on the Texecom panel, but if there are details needed to troubleshoot I can ask to my on-site team to send whatever is needed.

_Originally posted by @grillsoftware in https://github.com/dchesterton/texecom2mqtt-hassio/issues/34#issuecomment-963427458_

**Comment by dchesterton** [comment]
I think this might be a config issue. I've recently updated the app to provide better feedback on invalid config instead of the error you received. If you're still having this problem can you upgrade to the latest version and send me the log?
