### ISSUE TITLE
Update intro to include push notification disabled

### ISSUE THREAD

**Issue by whiteduck22** [dchesterton/texecom2mqtt-hassio#38]
Thanks for what you have done but I wonder if it would make sense to add the note that when this is running the usual push notifications when setting or disabling via the keypad or app are disabled. I know this is a limitation of the Texecom smartcom rather than your code but useful to know. All the best. Ian

**Comment by whiteduck22** [comment]
Sorry I appreciate you mention this com port limitation under the troubleshooting section but it's not necessarily clear that push notifications are also disabled as soon as it's bound to MQTT.

**Comment by dchesterton** [comment]
Thanks Ian, I've updated the README and moved this to the top of the documentation so people are aware.
