### ISSUE TITLE
Question : Can you have two smartcoms installed?

### ISSUE THREAD

**Issue by asantaga** [dchesterton/texecom2mqtt-hassio#39]
From reading the FAQ section I read that you can only have one com port used by one app at a time

If you have the smartcom 4g, can you have MQTT bound to Wifi port and Texecom Cloud connected to 4g?

or do I need two seperate com units?

**Comment by trullock** [comment]
You can buy a ComWIFI/ComIP and attach it to Com3 (if your panel has one) to give you the additional TCP socket

**Comment by asantaga** [comment]
Thanks ComWifi would work, I see these on ebay for £25-35 and would solve the issue of the app notifications not working.
