### ISSUE TITLE
Ricochet Device Battery Level

### ISSUE THREAD

**Issue by RogerSelwyn** [dchesterton/texecom2mqtt-hassio#4]
Is it possible to get the battery levels for Ricochet devices (I have a Bell and Motion Sensor), because that would make it easier to alert when the batteries need replacing?

Thanks for your work.

**Comment by dchesterton** [comment]
Unfortunately this isn't exposed via the Texecom API. If it was exposed by Texecom, I'd happily add it as it would definitely be useful.
