### ISSUE TITLE
Add support for MQTT TLS insecure debug

### ISSUE THREAD

**Issue by mdidon** [dchesterton/texecom2mqtt-hassio#40]
@dchesterton Testing with MQTT in a local environment with TLS enabled.
It is often useful for debugging purposes to be able to bypass the self signed check.
Please allow access to the tls_insecure/rejectUnauthorized property.

**Comment by dchesterton** [comment]
Thanks for the suggestion. This has been added in v1.1.9: https://github.com/dchesterton/texecom2mqtt-hassio/releases/tag/v1.1.9
