### ISSUE TITLE
Question: Can the alarm be triggered via texecom2mqtt ?

### ISSUE THREAD

**Issue by rob1981forest** [dchesterton/texecom2mqtt-hassio#41]
A question not an issue but not sure where general questions go.

Can the alarm be triggered via the integration at all ? I'm essentially thinking of getting a £7 ikea zigbee button and using that as a panic button to trigger the alarm using HA / nodered.

Thanks in advance.

Rob

**Comment by dchesterton** [comment]
Hi Rob, unfortunately there is no way to do this in the API as per the documentation I have. I've noticed it is possible to do this via the official Texecom Connect app so there must be support but there's nothing in the documentation I've been provided by Texecom.
