### ISSUE TITLE
Unable to install via add on store

### ISSUE THREAD

**Issue by MThomas564** [dchesterton/texecom2mqtt-hassio#42]
Attempting to install the add on via the add on store. Unable to do so with the following error showing in log:

WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/c15a2434/config.json: does not match regular expression ^(?:|bool|email|url|port|device(?:\((?P<filter>subsystem=[a-z]+)\))?|str(?:\((?P<s_min>\d+)?,(?P<s_max>\d+)?\))?|password(?:\((?P<p_min>\d+)?,(?P<p_max>\d+)?\))?|int(?:\((?P<i_min>\d+)?,(?P<i_max>\d+)?\))?|float(?:\((?P<f_min>[\d\.]+)?,(?P<f_max>[\d\.]+)?\))?|match\((?P<match>.*)\)|list\((?P<list>.+)\))\??$ for dictionary value @ data['schema']['mqtt']['prefix']. Got 'string?'

**Comment by dchesterton** [comment]
Thanks for reporting. This should be fixed now. You may need to reload the add-ons for it to work.
