### ISSUE TITLE
ERROR: Could not log in to panel

### ISSUE THREAD

**Issue by trullock** [dchesterton/texecom2mqtt-hassio#43]
**Describe the bug**
Regardless of my woes with #36 I am now no longer even able to "log in".

I can connect to the same Texecom `host:port` wia Wintex

**Application version**
v1.1.14 - not sure if this is the version which broke it

**Texecom alarm type**
Premier Elite 64 V5.00.03 LS1

**Home Assistant version**
Latest as of right now
Doesn't matter, just booting the add-on container directly also suffers the same fate

**Debug log**
```
2022-01-05 20:08:56 - INFO: Starting texecom2mqtt v1.1.14 (Node v16.13.0)...
2022-01-05 20:08:56 - INFO: Connected to alarm, sleeping for 2 seconds...
2022-01-05 20:08:58 - DEBUG: Executing serial number command
2022-01-05 20:08:59 - TRACE: Received data chunk of length 11
2022-01-05 20:08:59 - INFO: Connection ready
2022-01-05 20:08:59 - INFO: Logging in to panel
2022-01-05 20:08:59 - TRACE: Executing command 1
2022-01-05 20:08:59 - TRACE: Received data chunk of length 7
2022-01-05 20:08:59 - ERROR: Could not log in to panel
2022-01-05 20:08:59 - DEBUG: Closing connection to panel
2022-01-05 20:08:59 - DEBUG: Closed connection to panel
```

After some sniffing with wireshark the response that comes back from the login command is: `0x7452070001150a`.

I can see the Panel serial number comes back, so the TCP connection has definitely been established and the panel is communicating

**Comment by dchesterton** [comment]
Thanks for the detailed report. Unfortunately the `0x7452070001150a` response is an invalid login response from the panel so I don't think this is an issue with the add-on. I've not touched any of the code around login either.

**Comment by trullock** [comment]
Thanks

I've just run a health check via Texecom Cloud and despire saying "Healthy" it reports:

![image](https://user-images.githubusercontent.com/118878/148288216-e00a1fa3-6c2c-4958-905b-ab7cf245cbd2.png)

Do you know what this means or what to do about it? I can't find a shred of info online

**Comment by dchesterton** [comment]
The only thing I can find is "If more than three attempts at reporting are made with a wrong password, the modem will lock out for 4 hours or until a Master User code is entered." in the Premier Elite installation manual.

**Comment by trullock** [comment]
Ughh

just gonna buy some zigbee PIRs at this rate and make my own alarm with HA!

Thanks for your hard work on this, sorry for the red herring.

Why does Wintex work though???? Ughh arcane proprietary systems :'(
