### ISSUE TITLE
Full Arm issue from Home Assistant

### ISSUE THREAD

**Issue by joshward9182** [dchesterton/texecom2mqtt-hassio#44]
**Describe the bug**
I have 'full_arm' mapped to 'armed_away' in Home Assistant config (screenshot below).
It successfully detects as 'armed_away' in the alarm_control_panel entity, when I manually arm with the Texecom keypad.

However, when trying in Home Assistant, it arms it in to the part_arm_1 mode. This happens with both the 'alarm_control_panel.alarm_arm_away' service and a manual publish to the relevant MQTT topic (with 'full_arm' as payload).

**Application version**
1.1.15
_config below_
![Screenshot_20220108-194223.jpg](https://user-images.githubusercontent.com/69898979/148658024-9dba4fb2-6812-450c-a2ec-fc59ca0e6a9c.jpg)

**Texecom alarm type**
Premier Elite 48

**Home Assistant version**
2021.12.8

**Debug log**
![Screenshot_20220108-195155.jpg](https://user-images.githubusercontent.com/69898979/148658008-f87a00e7-b215-447f-8cfa-30a1165ac78e.jpg)

**Comment by dchesterton** [comment]
This is really odd. I use the exact same setup (full_arm = armed_away) which works as expected and I've never had a report of the app doing this before. The only thing I can assume is that your panel is configured differently?

**Comment by joshward9182** [comment]
I just went through and started messing with some settings and you were right, it was a panel setting..
This was the culprit:
![IMG_20220112_151901__01.jpg](https://user-images.githubusercontent.com/69898979/149168813-25205958-34ea-4646-8287-9eb305c2332f.jpg)

Apologies for raising this as an issue and appreciate the response 🙂

**Comment by dchesterton** [comment]
No problem, glad you've got it sorted 🙂
