### ISSUE TITLE
Do motion (PIR) sensors only report motion when the alarm is armed?

### ISSUE THREAD

**Issue by trullock** [dchesterton/texecom2mqtt-hassio#46]
My motion sensors are always reporting `off` when the alarm is disarmed (untested when armed - kids are in bed - but they do trigger the alarm!)

Presumably this is by design in the panel an not a bug with this?

**Comment by trullock** [comment]
I'm refering to IR motion sensors in this case, thanks

**Comment by trullock** [comment]
Ah, misunderstood your acronyms.

Hmm mine don't look like any of those, perhaps theyre an older model

**Comment by simontrimmer** [comment]
All good - mine are a bit older too and have slightly different cases to the current ones.

Was just observing that the different units seem to behave differently (and may have changed over the years internally too) e.g. the QD model could be used as room presence detectors but the DT model wouldn't work so well 👍
