### ISSUE TITLE
No updates from panel / restarting often helps

### ISSUE THREAD

**Issue by mrwee** [dchesterton/texecom2mqtt-hassio#5]
I often find that I don't get any updates from the panel. Restarting texecom2mqtt often helps.
The logfile states:
20-12-02 10:08:00 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with c15a2434_texecom2mqtt!

Logging is set to 0, but how can I see all the details? The log windows doesn't say much.

**Comment by perimore** [comment]
Read the doc here:

https://hub.docker.com/r/dchesterton/texecom2mqtt

And add the following to your config

```
# Optional: the log level (0 = debug, 1 = panel logs, 2 = info, 3 = warning, 4 = error) (default: 2)
log: 0
```

**Comment by mrwee** [comment]
Log was already set to 0.
My config is:
```
texecom:
  host: 192.168.xx.xx
  udl_password: 'xxxx'
  port: 10001
mqtt:
  host: 'mqtt://192.168.xx.xx:1883'
  username: null
  password: null
  client_id: texecom2mqtt
  keepalive: 30
  retain: false
  retain_log: true
  qos: 2
homeassistant:
  discovery: true
  prefix: homeassistant
log: 0
```

so everything should be fine. It also retrieves and MQTT publishes the panel power:
```
2020-12-15 21:31:38 - DEBUG: Updating system power...
2020-12-15 21:31:38 - DEBUG: Executing command 25
2020-12-15 21:31:38 - DEBUG: Publishing to texecom2mqtt/1046805/power: {"battery_charging_current":9,"battery_voltage":13.56,"panel_current":828,"panel_voltage":13.63}
```

or a sensor:
```
2020-12-15 21:28:57 - INFO: PIR gang status changed to Active
2020-12-15 21:28:57 - DEBUG: Publishing to texecom2mqtt/1046805/zone/pir_gang: {"name":"PIR gang","number":21,"areas":[1],"status":1,"type":"Guard"}
2020-12-15 21:29:02 - INFO: PIR gang status changed to Secure
2020-12-15 21:29:02 - DEBUG: Publishing to texecom2mqtt/1046805/zone/pir_gang: {"name":"PIR gang","number":21,"areas":[1],"status":0,"type":"Guard"}
```

but the entities in hass does not get updated. That may take a long time (don't know what triggers the update), sometimes never.
![image](https://user-images.githubusercontent.com/6720774/102269902-9452fc00-3f1d-11eb-9d73-6acdd0019fcc.png)

**Comment by perimore** [comment]
One question, is that PIR a ricochet/wireless device?

**Comment by mrwee** [comment]
No, everything is hardwired. 
After some time, zones are updated now. I did not do anything to affect that.
I don't know if it is due to large amount of zones (Elite 168 panel). Is there some kind of additional logging which could be put in place?

**Comment by mrwee** [comment]
Do not know if it's related, but just found this in the home-assistant.log:
`2021-01-02 19:09:45 WARNING (MainThread) [homeassistant.components.mqtt.alarm_control_panel] Received unexpected payload: {"name":"Dog home","number":3,"status":"full_armed"}`

**Comment by madmic1314** [comment]
If you use an app to subscribe (either home assistant or MQTTBox) to the MQTT broker and topic you can watch what is being sent. Walk in front of a sensor and see if this is logged. If so then texecomconnect is sending the packet and the issue is with HA.

I've found that messing with this integration I ended up with a lot of sensors being created in HA like "Lounge_1" up to "Lounge_7"! Use the edit dashboard -> Unused sensors in HA to see what you have. It's a pain to get these renamed.

The unexpected payload is odd. In MQTTBox subscribe to the root mqtt topic "texecomconnect/#" and this will tell you everything that is sent by texecomconnect via MQTT.

**Comment by mrwee** [comment]
I've used MQTT Explorer and MQTT is updated fine. All topics under 'texecom2mqtt' look fine, but I don't know if the integration handles these correctly. Since Hass entities are still unavailable, despite MQTT being updated, something is out of sync. The unexpected payload might influence the stability, but I don't know.
Log is set to 0, but I don't see what I'd expect as "Debug" level logs. How can I see more details?

**Comment by dchesterton** [comment]
@mrwee you have debug level logs turned on based on the logs you posted before, e.g.

```
2020-12-15 21:29:02 - DEBUG: Publishing to texecom2mqtt/1046805/zone/pir_gang: {"name":"PIR gang","number":21,"areas":[1],"status":0,"type":"Guard"}
```

Is there a reason for setting `retain` to `false` in your config? Normally this should be `true` otherwise things can get out of sync. Please try updating that and if it's not working, post your full log and config here.

**Comment by mrwee** [comment]
@dchesterton No not really. But now that you mention it, it does make sense to have it enabled. I've done so, and will keep an eye on the status.

**Comment by mrwee** [comment]
@dchesterton The retain trick did a huge difference. Been working all weekend :)

I still get the area warning for area 3 (Received unexpected payload) though

**Comment by dchesterton** [comment]
Glad to hear it's working :)

Can you post your full config? I think the error might be that you haven't added the `areas` mapping in your Home Assistant config.
