### ISSUE TITLE
Two different unique IDs being created for device

### ISSUE THREAD

**Issue by B-Hartley** [dchesterton/texecom2mqtt-hassio#7]
Hi,

I seem to get two different IDs created for my panel when the home assistant add on starts.
Either 79131 or 1076889.

Is it getting a corrupted serial number or something?
Could the unique ID be forced in the config to prevent this occurring?

It creates a second set of entities and confuses my automations.

thanks

**Comment by madmic1314** [comment]
What's your config in the integration?

I noticed that if I change the prefix setting it doesn't always seem to obey this. Difficult to tell as the code is not available. I've left mine on the default "homeassistant" for now.

**Comment by B-Hartley** [comment]
I think it's the panel giving a corrupted response that is being interpreted as a different serial. 
Would be good if I could code the serial into the config so it doesn't change it. 

Thanks.

**Comment by oliver-simmons** [comment]
I have the same problem, I have noticed when this happens if I check the MQTT messages I see the status as offline for the incorrect serial number, can we either put a check to ignore status offline ? or ideally as @B-Hartley requested can we add the serial to the config?


2531110
status = offline

**Comment by dchesterton** [comment]
I've pushed an update which removes the serial number from the MQTT topic structure. Hopefully this should prevent the issue going forward.
