### ISSUE TITLE
TEXECOM GFA-0001 Texecom Connect SmartPlug Control?

### ISSUE THREAD

**Issue by perimore** [dchesterton/texecom2mqtt-hassio#8]
@dchesterton , would it be possible to expand control to these smart plugs?

I know there are cheaper and easier to integrate smart plugs out there but I'm having issues reaching a Richochet contact sensor at the end of the garden. I'm thinking this will help to expand the mesh by placing one on a wall at the rear of the house where I have smart plugs already.

Plus it would be nice cool to have this in your app :).

Thanks.

**Comment by dchesterton** [comment]
Thanks for the request but unfortunately I don't have any smart plugs or richochet devices so this isn't something I'm going to be able to add at this time, sorry. I'm not 100% sure there's support in the Texecom API to do this in any case.
